USE [master]
GO

/****** Object:  Database [CatalogoJogos]    Script Date: 12/10/2021 11:43:36 ******/
CREATE DATABASE [CatalogoJogos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CatalogoJogos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CatalogoJogos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CatalogoJogos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CatalogoJogos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CatalogoJogos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CatalogoJogos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CatalogoJogos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CatalogoJogos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CatalogoJogos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CatalogoJogos] SET ARITHABORT OFF 
GO

ALTER DATABASE [CatalogoJogos] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CatalogoJogos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CatalogoJogos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CatalogoJogos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CatalogoJogos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CatalogoJogos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CatalogoJogos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CatalogoJogos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CatalogoJogos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CatalogoJogos] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CatalogoJogos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CatalogoJogos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CatalogoJogos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CatalogoJogos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CatalogoJogos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CatalogoJogos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CatalogoJogos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CatalogoJogos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CatalogoJogos] SET  MULTI_USER 
GO

ALTER DATABASE [CatalogoJogos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CatalogoJogos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CatalogoJogos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CatalogoJogos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CatalogoJogos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CatalogoJogos] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CatalogoJogos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CatalogoJogos] SET  READ_WRITE 
GO

